spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teamwork?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: dudu
  batch:
    jdbc:
      table-prefix: teamwork