spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teamwork?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  batch:
    jdbc:
      table-prefix: teamwork

  web:
    resources:
      static-locations: classpath:/