spring:
  datasource:
    url: jdbc:mysql://localhost:3305/teamwork?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  batch:
    jdbc:
      table-prefix: teamwork